version: "3"
services:
  app:
    build:
      context: ./volo
      dockerfile: ./volo/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - es
      - recommend

  recommend:
    image: zhenghaoz/gorse-in-one:latest
    restart: always
    ports:
      - "8088:8088"
    command: >
      -c /etc/gorse/config.toml
      --log-path /var/log/gorse/master.log
      --cache-path /var/lib/gorse/master_cache.data
    volumes:
      - ./gorse/example.config.toml:/etc/gorse/config.toml # important !!
    depends_on:
      - cache
      - db
    
  cache:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: volo
      POSTGRES_PASSWORD: volo
    volumes:
      - ./gorse/schema.sql.sql:/docker-entrypoint-initdb.d/schema.sql # create schema for gorse
    ports:
      - "5432:5432"
  
  es:
    build: 
      context: ./elasticsearch
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=true"
      - "ELASTIC_PASSWORD=espwd"
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
    ports:
      - "9200:9200"
      - "9300:9300"