version: "3"
services:
  app:
    build:
      context: ./volo
    restart: always
    environment:
      DATABASE_URL: postgres://volo:volo@db:5432/volo?sslmode=disable
      NEXTAUTH_SECRET: '1234567890'
      QINIU_ACCESS_KEY: # required
      QINIU_SECRET_KEY: # required
      QINIU_BUCKET: volo # need pre-create
      GORSE_URL: http://recommend:8088
      REDIS_URL: redis://cache:6379/8
      ES_URL: http://es:9200
      INIT_DB: true # if need load mock dataset
    ports:
      - "3000:3000"
    depends_on:
      - db
      - cache
      - es
      - recommend

  recommend:
    image: zhenghaoz/gorse-in-one:latest
    restart: always
    ports:
      - 8088:8088
    command: >
      -c /etc/gorse/config.toml
      --log-path /var/log/gorse/master.log
      --cache-path /var/lib/gorse/master_cache.data
    volumes:
      - ./gorse/example.config.toml:/etc/gorse/config.toml # important !!
    depends_on:
      - cache
      - db
    
  cache:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: volo
      POSTGRES_PASSWORD: volo
      POSTGRES_DB: volo
    volumes:
      - ./gorse/schema.sql:/docker-entrypoint-initdb.d/schema.sql # create recommend schema for gorse
    ports:
      - "5432:5432"
  
  es:
    build: 
      context: ./elasticsearch
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
    ports:
      - "9200:9200"
      # - "9300:9300" if need to deploy cluster